parameters:
  default_responses:

    # PIM installation absolute path
    installation_path_source_pim: ''
    installation_path_destination_pim: ''

    # Only for remote source PIM
    ssh_hostname_source_pim: ''
    ssh_port_source_pim: '22'
    ssh_user_source_pim: ''
    ssh_passwd_source_pim: ''

    # Base URI (with http://) to request the API
    api_base_uri_source_pim: ''
    api_base_uri_destination_pim: ''

    # API authentication
    api_client_id: ''
    api_secret: ''
    api_user_name: ''
    api_user_pwd: ''
