services:
  _defaults:
    autoconfigure: true
    autowire: true

  _instanceof:
    Akeneo\PimMigration\Infrastructure\MigrationStep\StateMachineSubscriber:
      tags: ['migration_tool.subscriber']
    Akeneo\PimMigration\Domain\Command\Console:
      tags: ['migration_tool.console']
    Akeneo\PimMigration\Domain\FileFetcher:
      tags: ['migration_tool.file_fetcher']
    Akeneo\PimMigration\Domain\MigrationStep\s040_DestinationPimDownload\DestinationPimDownloader:
      tags: ['migration_tool.destination_pim_downloader']
    Akeneo\PimMigration\Domain\MigrationStep\s050_DestinationPimInstallation\DestinationPimSystemRequirementsInstaller:
      tags: ['migration_tool.destination_pim_system_requirements_installer']

  Akeneo\PimMigration\Infrastructure\MigrationStep\:
    resource: './../../MigrationStep/*'

### COMMAND

  Akeneo\PimMigration\Domain\Command\ChainedConsole: ~
  Akeneo\PimMigration\Infrastructure\Cli\LocalConsole: ~
  Akeneo\PimMigration\Infrastructure\Cli\SshConsole: ~

### DATA MIGRATION
  Akeneo\PimMigration\Domain\DataMigration\BundleConfigFetcher: ~
  Akeneo\PimMigration\Domain\DataMigration\EntityMappingChecker: ~
  Akeneo\PimMigration\Domain\DataMigration\EntityTableNameFetcher: ~
  Akeneo\PimMigration\Domain\DataMigration\TableMigrator: ~

### SOURCE PIM CONFIGURATION

  Akeneo\PimMigration\Domain\MigrationStep\s010_SourcePimConfiguration\SourcePimConfigurator: ~

### DESTINATION PIM DOWNLOAD

  Akeneo\PimMigration\Domain\MigrationStep\s040_DestinationPimDownload\DestinationPimDownloaderHelper: ~
  Akeneo\PimMigration\Infrastructure\DestinationPimDownload\GitDestinationPimDownloader: ~
  Akeneo\PimMigration\Infrastructure\DestinationPimDownload\LocalArchiveDestinationPimDownloader: ~
  Akeneo\PimMigration\Infrastructure\DestinationPimDownload\LocalDownloader: ~

### DESTINATION PIM INSTALLATION

  Akeneo\PimMigration\Domain\MigrationStep\s050_DestinationPimInstallation\DestinationPimConfigurationChecker: ~
  Akeneo\PimMigration\Domain\MigrationStep\s050_DestinationPimInstallation\DestinationPimConfigurator: ~
  Akeneo\PimMigration\Domain\MigrationStep\s050_DestinationPimInstallation\DestinationPimEditionChecker: ~
  Akeneo\PimMigration\Domain\MigrationStep\s050_DestinationPimInstallation\DestinationPimSystemRequirementsChecker: ~
  Akeneo\PimMigration\Domain\MigrationStep\s050_DestinationPimInstallation\DestinationPimSystemRequirementsInstallerHelper: ~
  Akeneo\PimMigration\Domain\MigrationStep\s050_DestinationPimInstallation\ParametersYamlGenerator: ~
  Akeneo\PimMigration\Infrastructure\DestinationPimInstallation\BasicDestinationPimSystemRequirementsInstaller: ~

### FILE System

  Akeneo\PimMigration\Domain\FileSystemHelper: ~
  Akeneo\PimMigration\Domain\FileFetcherRegistry: ~
  Akeneo\PimMigration\Infrastructure\LocalFileFetcher: ~
  Akeneo\PimMigration\Infrastructure\SshFileFetcher: ~

### STRUCTURE MIGRATORS

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\StructureMigrator: ~

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\LocaleStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_locale'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\CurrencyStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_currency'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\CategoryStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_category'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\CategoryTranslationStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_category_translation'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\AttributeGroupStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_attribute_group'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\AttributeGroupTranslationStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_attribute_group_translation'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\GroupTypeStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_group_type'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\GroupTypeStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_group_type_translation'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\ChannelStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_channel'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\ChannelCurrencyStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_channel_currency'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\ChannelLocaleStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_channel_locale'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\ChannelTranslationStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_channel_translation'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\AssociationTypeStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_association_type'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\AssociationTypeTranslationStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_association_type_translation'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\AttributeDataMigrator:
    class: 'Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\AttributeDataMigrator'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\AttributeLocal:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_attribute_locale'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\AttributeTranslation:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_attribute_translation'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\AttributeOption:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_attribute_option'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\AttributeOptionValue:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_attribute_option_value'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\AttributeRequirement:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_attribute_requirement'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\EeAssetCategory:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pimee_product_asset_category'
      $isEeOnly: true
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\EeAssetCategoryTranslation:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pimee_product_asset_category_translation'
      $isEeOnly: true
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\EeAssetTag:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pimee_product_asset_tag'
      $isEeOnly: true
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s070_StructureMigration\EeAssetChaennelVariationConfiguration:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pimee_product_asset_channel_variation_configuration'
      $isEeOnly: true
    tags: ['migration_tool.structure_migrator']

## SYSTEM MIGRATORS

  Akeneo\PimMigration\Domain\MigrationStep\s090_SystemMigration\SystemMigrator: ~

  Akeneo\PimMigration\Domain\MigrationStep\s090_SystemMigration\AclClasses:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'acl_classes'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s090_SystemMigration\AclSecurityIdentities:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'acl_security_identities'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s090_SystemMigration\AclObjectIdentities:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'acl_object_identities'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s090_SystemMigration\AclEntries:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'acl_entries'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s090_SystemMigration\AclObjectIdentityAncestors:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'acl_object_identity_ancestors'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s090_SystemMigration\OroAccessGroup:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'oro_access_group'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s090_SystemMigration\OroAccessRole:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'oro_access_role'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s090_SystemMigration\OroUserAccessGrouprole:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'oro_user_access_group_role'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s090_SystemMigration\OroUser:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'oro_user'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s090_SystemMigration\OroUserAccessGroup:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'oro_user_access_group'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s090_SystemMigration\OroUserAccessRole:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'oro_user_access_role'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s090_SystemMigration\OroConfig:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'oro_config'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s090_SystemMigration\OroConfigValue:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'oro_config_value'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s090_SystemMigration\PimApiAccessToken:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_api_access_token'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s090_SystemMigration\PimApiAuthCode:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_api_auth_code'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s090_SystemMigration\PimApiClient:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_api_client'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s090_SystemMigration\PimApiRefreshToken:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_api_refresh_token'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s090_SystemMigration\PimSession:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_session'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s090_SystemMigration\PimDatagridView:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_datagrid_view'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s090_SystemMigration\PimUserDefaultDatagridView:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_user_default_datagrid_view'
    tags: ['migration_tool.system_migrator']

### JOB MIGRATOR

  Akeneo\PimMigration\Domain\MigrationStep\s100_JobMigration\JobMigrator: ~

  Akeneo\PimMigration\Domain\MigrationStep\s100_JobMigration\AkeneoBatchJobInstance:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'akeneo_batch_job_instance'
    tags: ['migration_tool.job_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s100_JobMigration\AkeneoBatchJobExecution:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'akeneo_batch_job_execution'
    tags: ['migration_tool.job_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s100_JobMigration\AkeneoBatchStepExecution:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'akeneo_batch_step_execution'
    tags: ['migration_tool.job_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s100_JobMigration\AkeneoBatchWarning:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'akeneo_batch_warning'
    tags: ['migration_tool.job_migrator']

### GROUP MIGRATOR

  Akeneo\PimMigration\Domain\MigrationStep\s110_GroupMigration\GroupMigrator: ~

  Akeneo\PimMigration\Domain\MigrationStep\s110_GroupMigration\GroupType:
      class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
      arguments:
        $supportedTableName: 'pim_catalog_group_type'
      tags: ['migration_tool.group_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s110_GroupMigration\GroupTypeTranslation:
      class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
      arguments:
        $supportedTableName: 'pim_catalog_group_type_translation'
      tags: ['migration_tool.group_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s110_GroupMigration\Group:
      class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
      arguments:
        $supportedTableName: 'pim_catalog_group'
      tags: ['migration_tool.group_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s110_GroupMigration\GroupTranslation:
      class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
      arguments:
        $supportedTableName: 'pim_catalog_group_translation'
      tags: ['migration_tool.group_migrator']

  Akeneo\PimMigration\Domain\MigrationStep\s110_GroupMigration\GroupAttribute:
      class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
      arguments:
        $supportedTableName: 'pim_catalog_group_attribute'
      tags: ['migration_tool.group_migrator']

### EXTRA DATA MIGRATOR

  Akeneo\PimMigration\Domain\MigrationStep\s120_ExtraDataMigration\ExtraDataMigrator: ~

### REFERENCE DATA MIGRATOR

  Akeneo\PimMigration\Domain\MigrationStep\s130_ReferenceDataMigration\MigrationBundleInstaller: ~
  Akeneo\PimMigration\Domain\MigrationStep\s130_ReferenceDataMigration\ReferenceDataConfigurator: ~

### PRODUCT MIGRATOR

  Akeneo\PimMigration\Domain\MigrationStep\s140_ProductMigration\ProductMigrator:
    arguments:
      $batchSize: 100
      $productAssociationMigrator: '@Akeneo\PimMigration\Domain\MigrationStep\s140_ProductMigration\ProductAssociationMigrator'

  Akeneo\PimMigration\Domain\MigrationStep\s140_ProductMigration\ProductAssociationMigrator:
    arguments:
      $batchSize: 100
