services:
  _defaults:
    autoconfigure: true

  _instanceof:
    Akeneo\PimMigration\Infrastructure\StateMachineTransition\StateMachineSubscriber:
      tags: ['migration_tool.subscriber']

  Akeneo\PimMigration\Infrastructure\StateMachineTransition\:
    resource: './../../StateMachineTransition/*'
